version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
      - "8088:8088"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    container_name: postgres-db
    networks:
      - app-network
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: testing
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    environment:
      REDIS_PASSWORD: root

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
